---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "localsight.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: localsight
    kubernetes.io/component: localsight
    kubernetes.io/name: localsight
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: localsight
      app.kubernetes.io/name: localsight
  template:
    metadata:
      labels:
        app.kubernetes.io/component: localsight
        app.kubernetes.io/name: localsight
    spec:
      hostNetwork: true
      containers:
        - name: exporter-container
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.config.port }}
              name: metrics
              protocol: TCP
          env:
            - name: LSE_PORT
              value: "{{ .Values.config.port }}"
            - name: LSE_DEBUG
              value: "{{ .Values.config.debug }}"
            - name: LSE_INTERVAL
              value: "{{ .Values.config.interval }}"
            - name: LSE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          volumeMounts:
            - name: kubelet-pki
              mountPath: /var/lib/kubelet/pki
              readOnly: true
      volumes:
        - name: kubelet-pki
          hostPath:
            path: /var/lib/kubelet/pki
            type: Directory
      terminationGracePeriodSeconds: 30
