---
{{- if .Values.servicemonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: localsight-service-monitor
    app.kubernetes.io/name: localsight
  name: {{ include "localsight.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
  - honorLabels: false
    interval: {{ .Values.servicemonitor.interval }}
    path: /metrics
    port: metrics
    relabelings: []
  namespaceSelector:
    matchNames:
    - {{ .Values.servicemonitor.namespaceSelector }}
  selector:
    matchLabels:
      app.kubernetes.io/component: localsight-service
      app.kubernetes.io/name: localsight
{{- end }}
